name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  python-hello-world:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: action/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install Dependencies
      run: python -c "print('Hello world')"
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
